CREATE TABLE "boa"."aggregation_centres" (
	"id" serial PRIMARY KEY NOT NULL,
	"ref_id" text NOT NULL,
	"application_id" integer,
	"centre_name" text NOT NULL,
	"centre_type" text NOT NULL,
	"reg_number" text,
	"tin_number" text,
	"year_established" integer,
	"owner_name" text,
	"owner_phone" text,
	"owner_nin" text,
	"commodities" text,
	"capacity_mt" real,
	"cold_storage_capacity_mt" real,
	"num_bays" integer,
	"floor_area_sqm" real,
	"warehouse_type" text,
	"facilities" text,
	"power_source" text,
	"water_source" text,
	"has_access_road" boolean,
	"warehouse_receipt_capable" boolean,
	"state" text NOT NULL,
	"lga" text,
	"address" text,
	"gps_lat" text,
	"gps_lng" text,
	"manager_name" text,
	"manager_phone" text,
	"manager_nin" text,
	"manager_email" text,
	"bank_name" text,
	"account_number" text,
	"bvn" text,
	"status" text DEFAULT 'active' NOT NULL,
	"approved_by" integer,
	"approved_at" text,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now() NOT NULL,
	CONSTRAINT "aggregation_centres_ref_id_unique" UNIQUE("ref_id")
);
--> statement-breakpoint
CREATE TABLE "boa"."applications" (
	"id" serial PRIMARY KEY NOT NULL,
	"ref_id" text NOT NULL,
	"centre_name" text NOT NULL,
	"centre_type" text NOT NULL,
	"reg_number" text,
	"tin_number" text,
	"year_established" integer,
	"owner_name" text,
	"owner_phone" text,
	"owner_nin" text,
	"commodities" text,
	"capacity_mt" real,
	"cold_storage_capacity_mt" real,
	"num_bays" integer,
	"floor_area_sqm" real,
	"warehouse_type" text,
	"facilities" text,
	"power_source" text,
	"water_source" text,
	"has_access_road" boolean,
	"warehouse_receipt_capable" boolean,
	"address" text,
	"state" text,
	"lga" text,
	"gps_lat" text,
	"gps_lng" text,
	"manager_name" text,
	"manager_phone" text,
	"manager_nin" text,
	"manager_email" text,
	"bank_name" text,
	"account_number" text,
	"bvn" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"review_notes" text,
	"reviewed_by" integer,
	"reviewed_at" text,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now() NOT NULL,
	CONSTRAINT "applications_ref_id_unique" UNIQUE("ref_id")
);
--> statement-breakpoint
CREATE TABLE "boa"."collection_requests" (
	"id" serial PRIMARY KEY NOT NULL,
	"ref_id" text NOT NULL,
	"farmer_name" text NOT NULL,
	"farmer_phone" text NOT NULL,
	"farmer_nin" text,
	"address" text NOT NULL,
	"state" text NOT NULL,
	"lga" text NOT NULL,
	"commodity" text NOT NULL,
	"estimated_quantity_kg" real NOT NULL,
	"collection_type" text NOT NULL,
	"preferred_date" text NOT NULL,
	"preferred_time" text,
	"notes" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"centre_id" integer,
	"centre_name" text,
	"collector_id" integer,
	"collector_name" text,
	"assigned_at" text,
	"in_transit_at" text,
	"collected_at" text,
	"actual_quantity_kg" real,
	"collection_notes" text,
	"gps_lat" text,
	"gps_lng" text,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now() NOT NULL,
	CONSTRAINT "collection_requests_ref_id_unique" UNIQUE("ref_id")
);
--> statement-breakpoint
CREATE TABLE "boa"."commodity_intakes" (
	"id" serial PRIMARY KEY NOT NULL,
	"ref_id" text NOT NULL,
	"centre_id" integer NOT NULL,
	"centre_name" text NOT NULL,
	"commodity" text NOT NULL,
	"quantity_kg" real NOT NULL,
	"grade_quality" text,
	"farmer_name" text,
	"farmer_phone" text,
	"farmer_nin" text,
	"source_state" text,
	"source_lga" text,
	"source_type" text DEFAULT 'farmer' NOT NULL,
	"supplier_id" integer,
	"supplier_name" text,
	"notes" text,
	"logged_by" integer NOT NULL,
	"created_at" text DEFAULT now() NOT NULL,
	CONSTRAINT "commodity_intakes_ref_id_unique" UNIQUE("ref_id")
);
--> statement-breakpoint
CREATE TABLE "boa"."farm_input_sales" (
	"id" serial PRIMARY KEY NOT NULL,
	"ref_id" text NOT NULL,
	"centre_id" integer NOT NULL,
	"centre_name" text NOT NULL,
	"input_id" integer NOT NULL,
	"input_name" text NOT NULL,
	"input_type" text NOT NULL,
	"quantity_sold" real NOT NULL,
	"unit" text NOT NULL,
	"price_per_unit" real NOT NULL,
	"total_amount" real NOT NULL,
	"buyer_name" text,
	"buyer_phone" text,
	"buyer_nin" text,
	"payment_method" text DEFAULT 'cash' NOT NULL,
	"receipt_number" text NOT NULL,
	"sold_by" integer NOT NULL,
	"notes" text,
	"created_at" text DEFAULT now() NOT NULL,
	CONSTRAINT "farm_input_sales_ref_id_unique" UNIQUE("ref_id")
);
--> statement-breakpoint
CREATE TABLE "boa"."farm_inputs" (
	"id" serial PRIMARY KEY NOT NULL,
	"ref_id" text NOT NULL,
	"centre_id" integer NOT NULL,
	"centre_name" text NOT NULL,
	"supplier_id" integer,
	"supplier_name" text,
	"input_type" text NOT NULL,
	"input_name" text NOT NULL,
	"brand" text,
	"unit" text DEFAULT 'kg' NOT NULL,
	"quantity_received" real NOT NULL,
	"quantity_available" real NOT NULL,
	"quantity_sold" real DEFAULT 0 NOT NULL,
	"purchase_price_per_unit" real,
	"selling_price_per_unit" real,
	"received_by" integer NOT NULL,
	"received_at" text NOT NULL,
	"notes" text,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now() NOT NULL,
	CONSTRAINT "farm_inputs_ref_id_unique" UNIQUE("ref_id")
);
--> statement-breakpoint
CREATE TABLE "boa"."inventory_sales" (
	"id" serial PRIMARY KEY NOT NULL,
	"ref_id" text NOT NULL,
	"centre_id" integer NOT NULL,
	"centre_name" text NOT NULL,
	"intake_id" integer NOT NULL,
	"commodity" text NOT NULL,
	"quantity_kg" real NOT NULL,
	"price_per_kg" real NOT NULL,
	"total_amount" real NOT NULL,
	"buyer_name" text,
	"buyer_phone" text,
	"payment_method" text DEFAULT 'cash' NOT NULL,
	"receipt_number" text NOT NULL,
	"sold_by" integer NOT NULL,
	"notes" text,
	"created_at" text DEFAULT now() NOT NULL,
	CONSTRAINT "inventory_sales_ref_id_unique" UNIQUE("ref_id")
);
--> statement-breakpoint
CREATE TABLE "boa"."loan_applications" (
	"id" serial PRIMARY KEY NOT NULL,
	"ref_id" text NOT NULL,
	"receipt_id" integer NOT NULL,
	"receipt_number" text NOT NULL,
	"centre_id" integer NOT NULL,
	"centre_name" text NOT NULL,
	"commodity" text NOT NULL,
	"quantity_kg" real NOT NULL,
	"farmer_name" text NOT NULL,
	"farmer_phone" text,
	"farmer_nin" text,
	"loan_amount_requested" real NOT NULL,
	"loan_amount_approved" real,
	"interest_rate" real,
	"repayment_period_months" integer,
	"status" text DEFAULT 'pending' NOT NULL,
	"reviewed_by" integer,
	"review_notes" text,
	"disbursed_at" text,
	"repaid_at" text,
	"created_at" text DEFAULT now() NOT NULL,
	CONSTRAINT "loan_applications_ref_id_unique" UNIQUE("ref_id")
);
--> statement-breakpoint
CREATE TABLE "boa"."notifications" (
	"id" serial PRIMARY KEY NOT NULL,
	"type" text NOT NULL,
	"message" text NOT NULL,
	"application_ref_id" text,
	"created_at" text DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "boa"."suppliers" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"phone" text,
	"email" text,
	"address" text,
	"state" text,
	"lga" text,
	"supplier_type" text DEFAULT 'individual' NOT NULL,
	"centre_id" integer,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "boa"."users" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"name" text NOT NULL,
	"role" text DEFAULT 'admin' NOT NULL,
	"centre_id" integer,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" text DEFAULT now() NOT NULL,
	"updated_at" text DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "boa"."warehouse_receipts" (
	"id" serial PRIMARY KEY NOT NULL,
	"receipt_number" text NOT NULL,
	"centre_id" integer NOT NULL,
	"centre_name" text NOT NULL,
	"intake_id" integer,
	"commodity" text NOT NULL,
	"quantity_kg" real NOT NULL,
	"grade_quality" text,
	"farmer_name" text NOT NULL,
	"farmer_phone" text,
	"farmer_nin" text,
	"issued_by" integer NOT NULL,
	"issued_at" text NOT NULL,
	"expires_at" text,
	"status" text DEFAULT 'active' NOT NULL,
	"notes" text,
	"created_at" text DEFAULT now() NOT NULL,
	CONSTRAINT "warehouse_receipts_receipt_number_unique" UNIQUE("receipt_number")
);
